### ISSUE TITLE
undefined: minify.string

### ISSUE THREAD

**Issue by patlux** [olliephillips/espruingo#1]
Hi,

I get a error on `go get github.com/olliephillips/espruingo`.

``` bash
src/github.com/olliephillips/espruingo/espruingo.go:245: undefined: minify.String
```

System: Archlinux x64

**Comment by olliephillips** [comment]
Hi, thanks for trying this, and sorry to hear you are having issues. 

Looking at it, it looks like the author of the minify package has introduced some breaking changes in their  packages API (https://github.com/tdewolff/minify). I'll need to update my code to suit.

In the meantime, there is a 64 bit Linux binary in the repo. You could try that, though I totally understand if you'd rather compile it yourself. Alternatively, fork it and comment out line 118 of espruingo.go. That will remove the call to the minification function. 

Hope that's a bit helpful. I'll see about updating the package in the next week or so.

**Comment by patlux** [comment]
Thank you for your reply.

I tried the x64 (and the 32) binary with another error:

``` bash
line 4: syntax error near unexpected token `newline`
line 4: `<!DOCTYPE html>`
```

Goog idea! I will fork this project and remove the line for the meantime.

**Comment by olliephillips** [comment]
That's disappointing. I haven't tested most of the binaries (I can't) but was depending on the cross compilation features of Go to build useable binaries.  I'll get this fixed up as soon as possible. Thanks for flagging the issue(s)

**Comment by olliephillips** [comment]
This should be fixed now.
